			var carousel;
			FWDR3DCarUtils.onReady(function(){
				carousel = new FWDRoyal3DCarousel({
					//カルーセルを格納する場所
					carouselHolderDivId:"myDiv",
					//カルーセルの内容物
					carouselDataListDivId:"carouselData",
					//リキッドデザインかどうか？
					displayType:"responsive",
					//スケーリングの調整？
					autoScale:"no",
					//カルーセルの幅
					carouselWidth:1200,
					//カルーセルの高さ
					carouselHeight:430,
					//カルーセルのスキン
					skinPath:"http://mikeyasuana.com/spacelectro_web/wp-content/themes/twentythirteen/space_ver_2.0/3d_plagin/load/skin_modern_warm",
					//カルーセルのスタート位置
					carouselStartPosition:"left",
					//画面内のスライドコンテンツの表示件数
					numberOfThumbnailsToDisplayLeftAndRight:60,
					
					showSlideshowButton:"no",
					disableNextAndPrevButtonsOnMobile:"no",
					showContextMenu:"no",
					//下部にある制御バーの長さ
					controlsMaxWidth:840,
					//サムネイル画像の一つの大きさ
					thumbnailWidth:500,
					thumbnailHeight:500,
					//下部の反射の設定
					showReflection:"yes",
					reflectionHeight:60,
					reflectionDistance:0,
					reflectionOpacity:.2,
					//スクロールバーの設定
					
					disableScrollbarOnMobile:"yes",
					enableMouseWheelScroll:"yes",
					scrollbarHandlerWidth:70,
					scrollbarTextColorNormal:"#777777",
					scrollbarTextColorSelected:"#000000",
					//
					showText:"yes",
					showTextBackgroundImage:"no",
					showThumbnailBoxShadow:"no",
					thumbnailBoxShadowCss:"0px 2px 2px #555555",
					showReflection:"yes",
					reflectionHeight:60,
					reflectionDistance:0,
					reflectionOpacity:.2,
					showThumbnailsHtmlContent:"yes",
					enableMouseWheelScroll:"no",
					
					//UIボタンの表示設定
					showPrevButton:"no",
					showNextButton:"no",
					showScrollbar:"yes",
				});	
				carousel2 = new FWDRoyal3DCarousel({
					//カルーセルを格納する場所
					carouselHolderDivId:"myDiv2",
					//カルーセルの内容物
					carouselDataListDivId:"carouselData2",
					//リキッドデザインかどうか？
					displayType:"responsive",
					//スケーリングの調整？
					autoScale:"no",
					//カルーセルの幅
					carouselWidth:1200,
					//カルーセルの高さ
					carouselHeight:430,
					//カルーセルのスキン
					skinPath:"http://mikeyasuana.com/spacelectro_web/wp-content/themes/twentythirteen/space_ver_2.0/3d_plagin/load/skin_modern_warm",
					//カルーセルのスタート位置
					carouselStartPosition:"left",
					//画面内のスライドコンテンツの表示件数
					numberOfThumbnailsToDisplayLeftAndRight:40,
					showSlideshowButton:"no",
					disableNextAndPrevButtonsOnMobile:"no",
					showContextMenu:"no",
					//下部にある制御バーの長さ
					controlsMaxWidth:840,
					//サムネイル画像の一つの大きさ
					thumbnailWidth:500,
					thumbnailHeight:500,
					//下部の反射の設定
					showReflection:"yes",
					reflectionHeight:60,
					reflectionDistance:0,
					reflectionOpacity:.2,
					disableScrollbarOnMobile:"yes",
					enableMouseWheelScroll:"yes",
					scrollbarHandlerWidth:70,
					scrollbarTextColorNormal:"#777777",
					scrollbarTextColorSelected:"#000000",
					//
					showText:"yes",
					showTextBackgroundImage:"no",
					showThumbnailBoxShadow:"no",
					thumbnailBoxShadowCss:"0px 2px 2px #555555",
					showReflection:"yes",
					reflectionHeight:60,
					reflectionDistance:0,
					reflectionOpacity:.2,
					showThumbnailsHtmlContent:"yes",
					enableMouseWheelScroll:"no",
					//UIボタンの表示設定
					showPrevButton:"no",
					showNextButton:"no",
					showScrollbar:"yes",
				});	
				
					carousel3 = new FWDRoyal3DCarousel({
					//カルーセルを格納する場所
					carouselHolderDivId:"myDiv3",
					//カルーセルの内容物
					carouselDataListDivId:"carouselData3",
					//リキッドデザインかどうか？
					displayType:"responsive",
					//スケーリングの調整？
					autoScale:"no",
					//カルーセルの幅
					carouselWidth:1200,
					//カルーセルの高さ
					carouselHeight:430,
					//カルーセルのスキン
					skinPath:"http://mikeyasuana.com/spacelectro_web/wp-content/themes/twentythirteen/space_ver_2.0/3d_plagin/load/skin_modern_warm",
					//カルーセルのスタート位置
					carouselStartPosition:"left",
					//画面内のスライドコンテンツの表示件数
					numberOfThumbnailsToDisplayLeftAndRight:40,
					showSlideshowButton:"no",
					disableNextAndPrevButtonsOnMobile:"no",
					showContextMenu:"no",
					//下部にある制御バーの長さ
					controlsMaxWidth:840,
					//サムネイル画像の一つの大きさ
					thumbnailWidth:500,
					thumbnailHeight:500,
					//下部の反射の設定
					showReflection:"yes",
					reflectionHeight:60,
					reflectionDistance:0,
					reflectionOpacity:.2,
					disableScrollbarOnMobile:"yes",
					enableMouseWheelScroll:"yes",
					scrollbarHandlerWidth:70,
					scrollbarTextColorNormal:"#777777",
					scrollbarTextColorSelected:"#000000",
					//
					showText:"yes",
					showTextBackgroundImage:"no",
					showThumbnailBoxShadow:"no",
					thumbnailBoxShadowCss:"0px 2px 2px #555555",
					showReflection:"yes",
					reflectionHeight:60,
					reflectionDistance:0,
					reflectionOpacity:.2,
					showThumbnailsHtmlContent:"yes",
					enableMouseWheelScroll:"no",
					//UIボタンの表示設定
					showPrevButton:"no",
					showNextButton:"no",
					showScrollbar:"yes",
				});	
				carousel4 = new FWDRoyal3DCarousel({
					//カルーセルを格納する場所
					carouselHolderDivId:"myDiv4",
					//カルーセルの内容物
					carouselDataListDivId:"carouselData4",
					//リキッドデザインかどうか？
					displayType:"responsive",
					//スケーリングの調整？
					autoScale:"no",
					//カルーセルの幅
					carouselWidth:1200,
					//カルーセルの高さ
					carouselHeight:430,
					//カルーセルのスキン
					skinPath:"http://mikeyasuana.com/spacelectro_web/wp-content/themes/twentythirteen/space_ver_2.0/3d_plagin/load/skin_modern_warm",
					//カルーセルのスタート位置
					carouselStartPosition:"left",
					//画面内のスライドコンテンツの表示件数
					numberOfThumbnailsToDisplayLeftAndRight:40,
					showSlideshowButton:"no",
					disableNextAndPrevButtonsOnMobile:"no",
					showContextMenu:"no",
					//下部にある制御バーの長さ
					controlsMaxWidth:840,
					//サムネイル画像の一つの大きさ
					thumbnailWidth:500,
					thumbnailHeight:500,
					//下部の反射の設定
					showReflection:"yes",
					reflectionHeight:60,
					reflectionDistance:0,
					reflectionOpacity:.2,
					
					disableScrollbarOnMobile:"yes",
					enableMouseWheelScroll:"yes",
					scrollbarHandlerWidth:70,
					scrollbarTextColorNormal:"#777777",
					scrollbarTextColorSelected:"#000000",
					//
					showText:"yes",
					showTextBackgroundImage:"no",
					showThumbnailBoxShadow:"no",
					thumbnailBoxShadowCss:"0px 2px 2px #555555",
					showReflection:"yes",
					reflectionHeight:60,
					reflectionDistance:0,
					reflectionOpacity:.2,
					showThumbnailsHtmlContent:"yes",
					enableMouseWheelScroll:"no",
					//UIボタンの表示設定
					showPrevButton:"no",
					showNextButton:"no",
					showScrollbar:"yes",
				});	
				carousel5 = new FWDRoyal3DCarousel({
					//カルーセルを格納する場所
					carouselHolderDivId:"myDiv5",
					//カルーセルの内容物
					carouselDataListDivId:"carouselData5",
					//リキッドデザインかどうか？
					displayType:"responsive",
					//スケーリングの調整？
					autoScale:"no",
					//カルーセルの幅
					carouselWidth:1200,
					//カルーセルの高さ
					carouselHeight:430,
					//カルーセルのスキン
					skinPath:"http://mikeyasuana.com/spacelectro_web/wp-content/themes/twentythirteen/space_ver_2.0/3d_plagin/load/skin_modern_warm",
					//カルーセルのスタート位置
					carouselStartPosition:"left",
					//画面内のスライドコンテンツの表示件数
					numberOfThumbnailsToDisplayLeftAndRight:40,
					showSlideshowButton:"no",
					disableNextAndPrevButtonsOnMobile:"no",
					showContextMenu:"no",
					//下部にある制御バーの長さ
					controlsMaxWidth:840,
					//サムネイル画像の一つの大きさ
					thumbnailWidth:500,
					thumbnailHeight:500,
					//下部の反射の設定
					showReflection:"yes",
					reflectionHeight:60,
					reflectionDistance:0,
					reflectionOpacity:.2,
					disableScrollbarOnMobile:"yes",
					enableMouseWheelScroll:"yes",
					scrollbarHandlerWidth:70,
					scrollbarTextColorNormal:"#777777",
					scrollbarTextColorSelected:"#000000",
					//
					showText:"yes",
					showTextBackgroundImage:"no",
					showThumbnailBoxShadow:"no",
					thumbnailBoxShadowCss:"0px 2px 2px #555555",
					showReflection:"yes",
					reflectionHeight:60,
					reflectionDistance:0,
					reflectionOpacity:.2,
					showThumbnailsHtmlContent:"yes",
					enableMouseWheelScroll:"no",
					//UIボタンの表示設定
					showPrevButton:"no",
					showNextButton:"no",
					showScrollbar:"yes",
				});	
				/*
				setTimeout(function(){
					$("#myDiv img").wrap("<div class='package'></div>");
					$(".package").append("<li class='cd_case'><img src='./img/disco/cd_case.png' ></li><li class='shadow'><img src='./img/disco/cd_case_under.png' ></li>");
				},3000);
				*/
			})
			
			
			
			
			
			
			